[variables]
ZEPTOMAIL_API_KEY = "Zoho-enczapikey yA6KbHtZug30wGxWQUQ418CD8Iw1qKA8iCiz4SHiK5dxK4Xgi6Ft3kBvcIG6IjPS24/R4/9YathDJom7vo4MdpQ1Z4RWKpTGTuv4P2uV48xh8ciEYNYjgpqgB7EZG6RMch0nDig1RfMmWA=="
ZEPTOMAIL_FROM_EMAIL = "noreply@checkfirst.io"
ZEPTOMAIL_FROM_NAME = "CheckFirst TPRM"
